services:
  mysql:
    image: mysql:8.4
    container_name: auth-mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - auth-network

  redis:
    image: redis:8.0-alpine
    container_name: auth-redis
    restart: always
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    # 보안을 위해 requirepass
    command: sh -c "redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}"
    networks:
      - auth-network

  minio:
    image: minio/minio:latest
    container_name: auth-minio
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"   # API용
      - "9001:9001"   # 콘솔(Web UI)용
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
  minio_data: